"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import proto.clarifai.api.status.status_code_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    STACK_TRACE_FIELD_NUMBER: builtins.int
    PERCENT_COMPLETED_FIELD_NUMBER: builtins.int
    TIME_REMAINING_FIELD_NUMBER: builtins.int
    REQ_ID_FIELD_NUMBER: builtins.int
    INTERNAL_DETAILS_FIELD_NUMBER: builtins.int
    code: proto.clarifai.api.status.status_code_pb2.StatusCode.ValueType
    """Status code from internal codes."""

    description: typing.Text
    """A longer description of the error."""

    details: typing.Text
    """More details of the given error."""

    @property
    def stack_trace(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """For some environment we may return a stack trace to help debug
        any issues.
        """
        pass
    percent_completed: builtins.int
    """specifically for long running jobs"""

    time_remaining: builtins.int
    """if status is pending, how much time is remaining (in seconds)"""

    req_id: typing.Text
    """If we want to return a request id in the base status field"""

    internal_details: typing.Text
    """Internal Annotation (do not set in production, for internal Clarifai use only)."""

    def __init__(self,
        *,
        code: proto.clarifai.api.status.status_code_pb2.StatusCode.ValueType = ...,
        description: typing.Text = ...,
        details: typing.Text = ...,
        stack_trace: typing.Optional[typing.Iterable[typing.Text]] = ...,
        percent_completed: builtins.int = ...,
        time_remaining: builtins.int = ...,
        req_id: typing.Text = ...,
        internal_details: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","description",b"description","details",b"details","internal_details",b"internal_details","percent_completed",b"percent_completed","req_id",b"req_id","stack_trace",b"stack_trace","time_remaining",b"time_remaining"]) -> None: ...
global___Status = Status

class BaseResponse(google.protobuf.message.Message):
    """Base message to return when there is a internal server error that
    is not caught elsewhere.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def status(self) -> global___Status: ...
    def __init__(self,
        *,
        status: typing.Optional[global___Status] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...
global___BaseResponse = BaseResponse
