"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins

import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.extension_dict

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

CL_SHOW_IF_EMPTY_FIELD_NUMBER: builtins.int
CL_MORETAGS_FIELD_NUMBER: builtins.int
CL_DEFAULT_FLOAT_FIELD_NUMBER: builtins.int
DESCRIPTION_FIELD_NUMBER: builtins.int
cl_show_if_empty: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.FieldOptions, builtins.bool
]
"""If True then we will return this field with it's zero value even if not set.
This means in json responses empty lists will appear instead of not being returned (which is
the default convention for proto3). For int's we will show 0, for floats 0.0, etc.
"""
cl_moretags: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.FieldOptions, builtins.str
]
cl_default_float: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.FieldOptions, builtins.float
]
"""For float fields where this is set, this value will be used by the server when parsing the
request and the field is not present in the request. If the field is present in the request,
then the value of the field will be used instead. This is ONLY used for json requests as binary
proto requests are expected to always set the field.
"""
description: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[
    google.protobuf.descriptor_pb2.EnumValueOptions, builtins.str
]
"""A description of the enum value."""
