# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

cl_show_if_empty: google___protobuf___descriptor___FieldDescriptor = ...

cl_moretags: google___protobuf___descriptor___FieldDescriptor = ...

cl_default_float: google___protobuf___descriptor___FieldDescriptor = ...
