# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/utils/matrix.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%proto/clarifai/api/utils/matrix.proto\",\n\x0cMatrixUint64\x12\x0e\n\x06n_cols\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x04\x42\x46\n\x05utilsZ=github.com/Clarifai/clarifai-go-grpc/proto/clarifai/api/utilsb\x06proto3')



_MATRIXUINT64 = DESCRIPTOR.message_types_by_name['MatrixUint64']
MatrixUint64 = _reflection.GeneratedProtocolMessageType('MatrixUint64', (_message.Message,), {
  'DESCRIPTOR' : _MATRIXUINT64,
  '__module__' : 'proto.clarifai.api.utils.matrix_pb2'
  # @@protoc_insertion_point(class_scope:MatrixUint64)
  })
_sym_db.RegisterMessage(MatrixUint64)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\005utilsZ=github.com/Clarifai/clarifai-go-grpc/proto/clarifai/api/utils'
  _MATRIXUINT64._serialized_start=41
  _MATRIXUINT64._serialized_end=85
# @@protoc_insertion_point(module_scope)
