# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/utils/test_proto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from clarifai_grpc.grpc.api.utils import extensions_pb2 as proto_dot_clarifai_dot_api_dot_utils_dot_extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/clarifai/api/utils/test_proto.proto',
  package='clarifai.api.utils',
  syntax='proto3',
  serialized_options=b'\n\033com.clarifai.grpc.api.utilsP\001Z\005utils\242\002\004CAIP',
  serialized_pb=b'\n)proto/clarifai/api/utils/test_proto.proto\x12\x12\x63larifai.api.utils\x1a)proto/clarifai/api/utils/extensions.proto\"\xe5\x01\n\tTestProto\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x07message\x18\x02 \x01(\tB\x17\x80\xb5\x18\x01\x8a\xb5\x18\x0fprotos are cool\x12\x16\n\x05value\x18\x03 \x01(\x01\x42\x07\xd5\xb5\x18\x00\x00\x80?\x12\x13\n\x0bimage_bytes\x18\x04 \x01(\x0c\x12\x16\n\x0cstring_oneof\x18\x05 \x01(\tH\x00\x12\x14\n\nbool_oneof\x18\x06 \x01(\x08H\x00\x12\x37\n\rmessage_oneof\x18\x07 \x01(\x0b\x32\x1e.clarifai.api.utils.TestProto2H\x00\x42\x0e\n\x0cone_of_field\"&\n\nTestProto2\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66lip\x18\x02 \x01(\x08\x42-\n\x1b\x63om.clarifai.grpc.api.utilsP\x01Z\x05utils\xa2\x02\x04\x43\x41IPb\x06proto3'
  ,
  dependencies=[proto_dot_clarifai_dot_api_dot_utils_dot_extensions__pb2.DESCRIPTOR,])




_TESTPROTO = _descriptor.Descriptor(
  name='TestProto',
  full_name='clarifai.api.utils.TestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='clarifai.api.utils.TestProto.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='clarifai.api.utils.TestProto.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\200\265\030\001\212\265\030\017protos are cool', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='clarifai.api.utils.TestProto.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\325\265\030\000\000\200?', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_bytes', full_name='clarifai.api.utils.TestProto.image_bytes', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_oneof', full_name='clarifai.api.utils.TestProto.string_oneof', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_oneof', full_name='clarifai.api.utils.TestProto.bool_oneof', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_oneof', full_name='clarifai.api.utils.TestProto.message_oneof', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='one_of_field', full_name='clarifai.api.utils.TestProto.one_of_field',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=109,
  serialized_end=338,
)


_TESTPROTO2 = _descriptor.Descriptor(
  name='TestProto2',
  full_name='clarifai.api.utils.TestProto2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='clarifai.api.utils.TestProto2.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flip', full_name='clarifai.api.utils.TestProto2.flip', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=378,
)

_TESTPROTO.fields_by_name['message_oneof'].message_type = _TESTPROTO2
_TESTPROTO.oneofs_by_name['one_of_field'].fields.append(
  _TESTPROTO.fields_by_name['string_oneof'])
_TESTPROTO.fields_by_name['string_oneof'].containing_oneof = _TESTPROTO.oneofs_by_name['one_of_field']
_TESTPROTO.oneofs_by_name['one_of_field'].fields.append(
  _TESTPROTO.fields_by_name['bool_oneof'])
_TESTPROTO.fields_by_name['bool_oneof'].containing_oneof = _TESTPROTO.oneofs_by_name['one_of_field']
_TESTPROTO.oneofs_by_name['one_of_field'].fields.append(
  _TESTPROTO.fields_by_name['message_oneof'])
_TESTPROTO.fields_by_name['message_oneof'].containing_oneof = _TESTPROTO.oneofs_by_name['one_of_field']
DESCRIPTOR.message_types_by_name['TestProto'] = _TESTPROTO
DESCRIPTOR.message_types_by_name['TestProto2'] = _TESTPROTO2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestProto = _reflection.GeneratedProtocolMessageType('TestProto', (_message.Message,), {
  'DESCRIPTOR' : _TESTPROTO,
  '__module__' : 'proto.clarifai.api.utils.test_proto_pb2'
  # @@protoc_insertion_point(class_scope:clarifai.api.utils.TestProto)
  })
_sym_db.RegisterMessage(TestProto)

TestProto2 = _reflection.GeneratedProtocolMessageType('TestProto2', (_message.Message,), {
  'DESCRIPTOR' : _TESTPROTO2,
  '__module__' : 'proto.clarifai.api.utils.test_proto_pb2'
  # @@protoc_insertion_point(class_scope:clarifai.api.utils.TestProto2)
  })
_sym_db.RegisterMessage(TestProto2)


DESCRIPTOR._options = None
_TESTPROTO.fields_by_name['message']._options = None
_TESTPROTO.fields_by_name['value']._options = None
# @@protoc_insertion_point(module_scope)
