# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class TestProto(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: typing___Text = ...
    message: typing___Text = ...
    value: builtin___float = ...
    image_bytes: builtin___bytes = ...
    string_oneof: typing___Text = ...
    bool_oneof: builtin___bool = ...

    @property
    def message_oneof(self) -> type___TestProto2: ...

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        message : typing___Optional[typing___Text] = None,
        value : typing___Optional[builtin___float] = None,
        image_bytes : typing___Optional[builtin___bytes] = None,
        string_oneof : typing___Optional[typing___Text] = None,
        bool_oneof : typing___Optional[builtin___bool] = None,
        message_oneof : typing___Optional[type___TestProto2] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TestProto: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> TestProto: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bool_oneof",b"bool_oneof",u"message_oneof",b"message_oneof",u"one_of_field",b"one_of_field",u"string_oneof",b"string_oneof"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bool_oneof",b"bool_oneof",u"id",b"id",u"image_bytes",b"image_bytes",u"message",b"message",u"message_oneof",b"message_oneof",u"one_of_field",b"one_of_field",u"string_oneof",b"string_oneof",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"one_of_field",b"one_of_field"]) -> typing_extensions___Literal["string_oneof","bool_oneof","message_oneof"]: ...
type___TestProto = TestProto

class TestProto2(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: typing___Text = ...
    flip: builtin___bool = ...

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        flip : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TestProto2: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> TestProto2: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"flip",b"flip",u"id",b"id"]) -> None: ...
type___TestProto2 = TestProto2
