# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/utils/time.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/clarifai/api/utils/time.proto\x12\x12\x63larifai.api.utils\"K\n\tTimeOfDay\x12\r\n\x05hours\x18\x01 \x01(\x05\x12\x0f\n\x07minutes\x18\x02 \x01(\x05\x12\x0f\n\x07seconds\x18\x03 \x01(\x05\x12\r\n\x05nanos\x18\x04 \x01(\x05\"\xa0\x01\n\x0eTimeOfDayRange\x12,\n\x05start\x18\x01 \x01(\x0b\x32\x1d.clarifai.api.utils.TimeOfDay\x12*\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1d.clarifai.api.utils.TimeOfDay\x12\x1a\n\x12is_start_inclusive\x18\x03 \x01(\x08\x12\x18\n\x10is_end_inclusive\x18\x04 \x01(\x08\x42\\\n\x1b\x63om.clarifai.grpc.api.utilsZ=github.com/Clarifai/clarifai-go-grpc/proto/clarifai/api/utilsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.clarifai.api.utils.time_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.clarifai.grpc.api.utilsZ=github.com/Clarifai/clarifai-go-grpc/proto/clarifai/api/utils'
  _TIMEOFDAY._serialized_start=59
  _TIMEOFDAY._serialized_end=134
  _TIMEOFDAYRANGE._serialized_start=137
  _TIMEOFDAYRANGE._serialized_end=297
# @@protoc_insertion_point(module_scope)
