"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import sys

import google.protobuf.descriptor
import google.protobuf.message

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TimeOfDay(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOURS_FIELD_NUMBER: builtins.int
    MINUTES_FIELD_NUMBER: builtins.int
    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    hours: builtins.int
    """Hours of day in 24 hour format. Must be from 0 to 23."""
    minutes: builtins.int
    """Minutes of hour of day. Must be from 0 to 59."""
    seconds: builtins.int
    """Seconds of minutes of the time. Must be from 0 to 59."""
    nanos: builtins.int
    """Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999."""
    def __init__(
        self,
        *,
        hours: builtins.int = ...,
        minutes: builtins.int = ...,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "hours", b"hours", "minutes", b"minutes", "nanos", b"nanos", "seconds", b"seconds"
        ],
    ) -> None: ...

global___TimeOfDay = TimeOfDay

@typing_extensions.final
class TimeOfDayRange(google.protobuf.message.Message):
    """TimeOfDayRange represents a period of time withing a day.
    e.g. [9am, 5pm) -> start = 9:00:00, end = 17:00:00, is_start_inclusive = true, is_end_inclusive = false
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    IS_START_INCLUSIVE_FIELD_NUMBER: builtins.int
    IS_END_INCLUSIVE_FIELD_NUMBER: builtins.int
    @property
    def start(self) -> global___TimeOfDay:
        """Start time of day represented as a duration."""
    @property
    def end(self) -> global___TimeOfDay:
        """End time of day represented as a duration.
        May be less than start duration if the time of day range goes over midnight.
        """
    is_start_inclusive: builtins.bool
    is_end_inclusive: builtins.bool
    def __init__(
        self,
        *,
        start: global___TimeOfDay | None = ...,
        end: global___TimeOfDay | None = ...,
        is_start_inclusive: builtins.bool = ...,
        is_end_inclusive: builtins.bool = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["end", b"end", "start", b"start"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "end",
            b"end",
            "is_end_inclusive",
            b"is_end_inclusive",
            "is_start_inclusive",
            b"is_start_inclusive",
            "start",
            b"start",
        ],
    ) -> None: ...

global___TimeOfDayRange = TimeOfDayRange
