# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/auth/util/extension.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from clarifai_grpc.grpc.auth.scope import scope_pb2 as proto_dot_clarifai_dot_auth_dot_scope_dot_scope__pb2
from clarifai_grpc.grpc.auth.types import types_pb2 as proto_dot_clarifai_dot_auth_dot_types_dot_types__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(proto/clarifai/auth/util/extension.proto\x12\x12\x63larifai.auth.util\x1a%proto/clarifai/auth/scope/scope.proto\x1a%proto/clarifai/auth/types/types.proto\x1a google/protobuf/descriptor.proto:9\n\x10\x63l_private_field\x12\x1d.google.protobuf.FieldOptions\x18\xc0\xf3\x04 \x01(\x08:8\n\x0e\x63l_private_rpc\x12\x1e.google.protobuf.MethodOptions\x18\xc1\xf3\x04 \x01(\x08:U\n\x13\x63l_depending_scopes\x12\x1e.google.protobuf.MethodOptions\x18\xc2\xf3\x04 \x03(\x0e\x32\x16.clarifai.auth.scope.S:U\n\x0c\x63l_auth_type\x12\x1e.google.protobuf.MethodOptions\x18\xc3\xf3\x04 \x01(\x0e\x32\x1d.clarifai.auth.types.AuthType:=\n\x12\x63l_private_message\x12\x1f.google.protobuf.MessageOptions\x18\xc4\xf3\x04 \x01(\x08\x42\x65\n\x1b\x63om.clarifai.grpc.auth.utilP\x01Z=github.com/Clarifai/clarifai-go-grpc/proto/clarifai/auth/util\xa2\x02\x04\x43\x41IPb\x06proto3')


CL_PRIVATE_FIELD_FIELD_NUMBER = 80320
cl_private_field = DESCRIPTOR.extensions_by_name['cl_private_field']
CL_PRIVATE_RPC_FIELD_NUMBER = 80321
cl_private_rpc = DESCRIPTOR.extensions_by_name['cl_private_rpc']
CL_DEPENDING_SCOPES_FIELD_NUMBER = 80322
cl_depending_scopes = DESCRIPTOR.extensions_by_name['cl_depending_scopes']
CL_AUTH_TYPE_FIELD_NUMBER = 80323
cl_auth_type = DESCRIPTOR.extensions_by_name['cl_auth_type']
CL_PRIVATE_MESSAGE_FIELD_NUMBER = 80324
cl_private_message = DESCRIPTOR.extensions_by_name['cl_private_message']

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(cl_private_field)
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(cl_private_rpc)
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(cl_depending_scopes)
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(cl_auth_type)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(cl_private_message)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.clarifai.grpc.auth.utilP\001Z=github.com/Clarifai/clarifai-go-grpc/proto/clarifai/auth/util\242\002\004CAIP'
# @@protoc_insertion_point(module_scope)
