# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

cl_private_field: google___protobuf___descriptor___FieldDescriptor = ...

cl_private_rpc: google___protobuf___descriptor___FieldDescriptor = ...

cl_depending_scopes: google___protobuf___descriptor___FieldDescriptor = ...

cl_auth_type: google___protobuf___descriptor___FieldDescriptor = ...

cl_private_message: google___protobuf___descriptor___FieldDescriptor = ...
