"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.extension_dict
import proto.clarifai.auth.scope.scope_pb2
import proto.clarifai.auth.types.types_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

CL_PRIVATE_FIELD_FIELD_NUMBER: builtins.int
CL_PRIVATE_RPC_FIELD_NUMBER: builtins.int
CL_DEPENDING_SCOPES_FIELD_NUMBER: builtins.int
CL_AUTH_TYPE_FIELD_NUMBER: builtins.int
CL_PRIVATE_MESSAGE_FIELD_NUMBER: builtins.int
cl_private_field: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, builtins.bool]
"""indicates if this field should be private. If true, then internal use only. If False,
then publicly avaliable to world.
"""
cl_private_rpc: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MethodOptions, builtins.bool]
"""indicates if this rpc should be private. If true, then internal use only. If False,
then publicly available to world.
"""
cl_depending_scopes: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MethodOptions, google.protobuf.internal.containers.RepeatedScalarFieldContainer[proto.clarifai.auth.scope.scope_pb2.S.ValueType]]
"""For each grpc method we define a list of required low-level auth scopes that are needed
for the key that is issuing the request. These are checked at authorization time for the
request as one of the first things in the life of a request once it reaches out API
servers. There are additional checks for each scope when the resource is used throughout the
backend in order to protect that resource. For example, Inputs_Add protects the writes to the
inputs DB table. Since we know every PostInputs call needs to do that, we add Inputs_Add scope
to the cl_depending_scopes list for the PostInputs method.

This is only checked valid when used with KeyAuth cl_auth_type.

This should be the absolute minimum required scopes to make API calls with the method
that this options is used for. If there are some scopes that are needed some of the time
depending on the request, then leave those out as they will be checked at the tighest
possible portion of the codebase to protect that resource and won't effect every API call. For
example, the PostAnnotations call is often used to add concepts as well. If those concepts are
new, then the Concepts_Add scope will be needed. But since you don't always annotate with
concepts, it is not a hard requirements that Concepts_Add is used.
"""
cl_auth_type: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MethodOptions, proto.clarifai.auth.types.types_pb2.AuthType.ValueType]
"""This is the authorizer type for the endpoint our of multiple backend authorizers."""
cl_private_message: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, builtins.bool]
"""indicates if this message should be private. If true, then internal use only. If False,
then publicly avaliable to world.
"""
