# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/auth/types/types.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/clarifai/auth/types/types.proto',
  package='clarifai.auth.types',
  syntax='proto3',
  serialized_options=b'\n\034com.clarifai.grpc.auth.typesP\001Z\005types\242\002\004CAIP',
  serialized_pb=b'\n%proto/clarifai/auth/types/types.proto\x12\x13\x63larifai.auth.types*`\n\x08\x41uthType\x12\t\n\x05undef\x10\x00\x12\n\n\x06NoAuth\x10\x01\x12\x0b\n\x07KeyAuth\x10\x02\x12\x14\n\x10SessionTokenAuth\x10\x03\x12\r\n\tAdminAuth\x10\x04\x12\x0b\n\x07PATAuth\x10\x05\x42.\n\x1c\x63om.clarifai.grpc.auth.typesP\x01Z\x05types\xa2\x02\x04\x43\x41IPb\x06proto3'
)

_AUTHTYPE = _descriptor.EnumDescriptor(
  name='AuthType',
  full_name='clarifai.auth.types.AuthType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='undef', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoAuth', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KeyAuth', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SessionTokenAuth', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AdminAuth', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PATAuth', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=62,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_AUTHTYPE)

AuthType = enum_type_wrapper.EnumTypeWrapper(_AUTHTYPE)
undef = 0
NoAuth = 1
KeyAuth = 2
SessionTokenAuth = 3
AdminAuth = 4
PATAuth = 5


DESCRIPTOR.enum_types_by_name['AuthType'] = _AUTHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
