# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from clarifai_grpc.grpc.api import service_pb2 as proto_dot_clarifai_dot_api_dot_service__pb2
from clarifai_grpc.grpc.api.status import status_pb2 as proto_dot_clarifai_dot_api_dot_status_dot_status__pb2


class V2Stub(object):
  """
  Note: this is based on the google api format defined here. Please
  read this before contributing to this file and other *.proto files
  for the API.
  https://cloud.google.com/service-management/reference/rpc/google.api#google.api.HttpRule

  """

  def __init__(self, channel):
    from clarifai_grpc.channel.clarifai_channel import wrap_response_deserializer
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetConceptCounts = channel.unary_unary(
        '/clarifai.api.V2/GetConceptCounts',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetConceptCountsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptCountResponse),
        )
    self.GetConcept = channel.unary_unary(
        '/clarifai.api.V2/GetConcept',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetConceptRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleConceptResponse),
        )
    self.ListConcepts = channel.unary_unary(
        '/clarifai.api.V2/ListConcepts',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListConceptsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse),
        )
    self.PostConceptsSearches = channel.unary_unary(
        '/clarifai.api.V2/PostConceptsSearches',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostConceptsSearchesRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse),
        )
    self.PostConcepts = channel.unary_unary(
        '/clarifai.api.V2/PostConcepts',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostConceptsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse),
        )
    self.PatchConcepts = channel.unary_unary(
        '/clarifai.api.V2/PatchConcepts',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchConceptsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse),
        )
    self.GetInputCount = channel.unary_unary(
        '/clarifai.api.V2/GetInputCount',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetInputCountRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleInputCountResponse),
        )
    self.GetInput = channel.unary_unary(
        '/clarifai.api.V2/GetInput',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetInputRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleInputResponse),
        )
    self.ListInputs = channel.unary_unary(
        '/clarifai.api.V2/ListInputs',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListInputsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse),
        )
    self.PostInputs = channel.unary_unary(
        '/clarifai.api.V2/PostInputs',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostInputsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse),
        )
    self.PatchInputs = channel.unary_unary(
        '/clarifai.api.V2/PatchInputs',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchInputsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse),
        )
    self.DeleteInput = channel.unary_unary(
        '/clarifai.api.V2/DeleteInput',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteInputRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.DeleteInputs = channel.unary_unary(
        '/clarifai.api.V2/DeleteInputs',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteInputsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.PostModelOutputs = channel.unary_unary(
        '/clarifai.api.V2/PostModelOutputs',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelOutputsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiOutputResponse),
        )
    self.GetModel = channel.unary_unary(
        '/clarifai.api.V2/GetModel',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse),
        )
    self.GetModelOutputInfo = channel.unary_unary(
        '/clarifai.api.V2/GetModelOutputInfo',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse),
        )
    self.ListModels = channel.unary_unary(
        '/clarifai.api.V2/ListModels',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListModelsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelResponse),
        )
    self.PostModelsSearches = channel.unary_unary(
        '/clarifai.api.V2/PostModelsSearches',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelsSearchesRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelResponse),
        )
    self.PostModels = channel.unary_unary(
        '/clarifai.api.V2/PostModels',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse),
        )
    self.PatchModels = channel.unary_unary(
        '/clarifai.api.V2/PatchModels',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchModelsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelResponse),
        )
    self.DeleteModel = channel.unary_unary(
        '/clarifai.api.V2/DeleteModel',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteModelRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.DeleteModels = channel.unary_unary(
        '/clarifai.api.V2/DeleteModels',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteModelsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.ListModelInputs = channel.unary_unary(
        '/clarifai.api.V2/ListModelInputs',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListModelInputsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse),
        )
    self.GetModelVersion = channel.unary_unary(
        '/clarifai.api.V2/GetModelVersion',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelVersionRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelVersionResponse),
        )
    self.ListModelVersions = channel.unary_unary(
        '/clarifai.api.V2/ListModelVersions',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListModelVersionsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelVersionResponse),
        )
    self.PostModelVersions = channel.unary_unary(
        '/clarifai.api.V2/PostModelVersions',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelVersionsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse),
        )
    self.DeleteModelVersion = channel.unary_unary(
        '/clarifai.api.V2/DeleteModelVersion',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteModelVersionRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.GetModelVersionMetrics = channel.unary_unary(
        '/clarifai.api.V2/GetModelVersionMetrics',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelVersionMetricsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelVersionResponse),
        )
    self.PostModelVersionMetrics = channel.unary_unary(
        '/clarifai.api.V2/PostModelVersionMetrics',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelVersionMetricsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelVersionResponse),
        )
    self.GetWorkflow = channel.unary_unary(
        '/clarifai.api.V2/GetWorkflow',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetWorkflowRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleWorkflowResponse),
        )
    self.ListWorkflows = channel.unary_unary(
        '/clarifai.api.V2/ListWorkflows',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListWorkflowsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiWorkflowResponse),
        )
    self.PostWorkflows = channel.unary_unary(
        '/clarifai.api.V2/PostWorkflows',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostWorkflowsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiWorkflowResponse),
        )
    self.PatchWorkflows = channel.unary_unary(
        '/clarifai.api.V2/PatchWorkflows',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchWorkflowsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiWorkflowResponse),
        )
    self.DeleteWorkflow = channel.unary_unary(
        '/clarifai.api.V2/DeleteWorkflow',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteWorkflowRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.DeleteWorkflows = channel.unary_unary(
        '/clarifai.api.V2/DeleteWorkflows',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteWorkflowsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.PostWorkflowResults = channel.unary_unary(
        '/clarifai.api.V2/PostWorkflowResults',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostWorkflowResultsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.PostWorkflowResultsResponse),
        )
    self.GetKey = channel.unary_unary(
        '/clarifai.api.V2/GetKey',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetKeyRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleKeyResponse),
        )
    self.ListKeys = channel.unary_unary(
        '/clarifai.api.V2/ListKeys',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListKeysRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse),
        )
    self.ListAppKeys = channel.unary_unary(
        '/clarifai.api.V2/ListAppKeys',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListAppKeysRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse),
        )
    self.DeleteKey = channel.unary_unary(
        '/clarifai.api.V2/DeleteKey',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteKeyRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.PostKeys = channel.unary_unary(
        '/clarifai.api.V2/PostKeys',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostKeysRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse),
        )
    self.PatchKeys = channel.unary_unary(
        '/clarifai.api.V2/PatchKeys',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchKeysRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse),
        )
    self.GetApp = channel.unary_unary(
        '/clarifai.api.V2/GetApp',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetAppRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleAppResponse),
        )
    self.ListApps = channel.unary_unary(
        '/clarifai.api.V2/ListApps',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListAppsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiAppResponse),
        )
    self.DeleteApp = channel.unary_unary(
        '/clarifai.api.V2/DeleteApp',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteAppRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse),
        )
    self.PostApps = channel.unary_unary(
        '/clarifai.api.V2/PostApps',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostAppsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiAppResponse),
        )
    self.PatchApps = channel.unary_unary(
        '/clarifai.api.V2/PatchApps',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchAppsRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiAppResponse),
        )
    self.PostSearches = channel.unary_unary(
        '/clarifai.api.V2/PostSearches',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostSearchesRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiSearchResponse),
        )
    self.ListStatusCodes = channel.unary_unary(
        '/clarifai.api.V2/ListStatusCodes',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListStatusCodesRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.MultiStatusCodeResponse),
        )
    self.GetStatusCode = channel.unary_unary(
        '/clarifai.api.V2/GetStatusCode',
        request_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetStatusCodeRequest.SerializeToString,
        response_deserializer=wrap_response_deserializer(proto_dot_clarifai_dot_api_dot_service__pb2.SingleStatusCodeResponse),
        )


class V2Servicer(object):
  """
  Note: this is based on the google api format defined here. Please
  read this before contributing to this file and other *.proto files
  for the API.
  https://cloud.google.com/service-management/reference/rpc/google.api#google.api.HttpRule

  """

  def GetConceptCounts(self, request, context):
    """//////////////////////////////////////
    Concepts
    //////////////////////////////////////

    List all the concepts with their positive and negative counts
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConcept(self, request, context):
    """Get a specific concept from an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListConcepts(self, request, context):
    """List all the concepts.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostConceptsSearches(self, request, context):
    """Search over the concepts to find one or more you're looking for.
    This leverage the "body" parameter because we also have page and
    per_page as url query param variables in this request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostConcepts(self, request, context):
    """Add a concept to an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchConcepts(self, request, context):
    """Patch one or more concepts.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInputCount(self, request, context):
    """//////////////////////////////////////
    Inputs
    //////////////////////////////////////

    Patch one or more inputs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInput(self, request, context):
    """Get a specific input from an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListInputs(self, request, context):
    """List all the inputs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostInputs(self, request, context):
    """Add an input (or set of inputs) to an app.
    This call is synchronous if the PostInputsRequest contains exactly one image input. Otherwise,
    it is asynchronous.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchInputs(self, request, context):
    """Patch one or more inputs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteInput(self, request, context):
    """Delete a single input.  This call is synchronous.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteInputs(self, request, context):
    """Delete multiple inputs in one request.
    This call is asynchronous. Use DeleteInput if you want a synchronous version.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostModelOutputs(self, request, context):
    """Get predicted outputs from the model.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModel(self, request, context):
    """//////////////////////////////////////

    //////////////////////////////////////
    Models
    //////////////////////////////////////

    Get a specific model from an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelOutputInfo(self, request, context):
    """Get a the output info for a given model_id or model_id/version_id
    combo.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListModels(self, request, context):
    """List all the models.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostModelsSearches(self, request, context):
    """Search over the models to find one or more you're looking for.
    This leverage the "body" parameter because we also have page and
    per_page as url query param variables in this request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostModels(self, request, context):
    """Add a models to an app.
    FIXME(zeiler): this should have been a plural response.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchModels(self, request, context):
    """Patch one or more models.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteModel(self, request, context):
    """Delete a single model.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteModels(self, request, context):
    """Delete multiple models in one request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListModelInputs(self, request, context):
    """List all the inputs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelVersion(self, request, context):
    """//////////////////////////////////////

    //////////////////////////////////////
    Model versions
    //////////////////////////////////////

    Get a specific model from an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListModelVersions(self, request, context):
    """List all the models.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostModelVersions(self, request, context):
    """NOTE: inconsistency: do we want this to return a SingleModelResponse?

    Create a new model version to trigger training of the model.
    FIXME(zeiler): this should have been a plural response.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteModelVersion(self, request, context):
    """Delete a single model.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelVersionMetrics(self, request, context):
    """Get the evaluation metrics for a model version.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostModelVersionMetrics(self, request, context):
    """Get the evaluation metrics for a model version.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWorkflow(self, request, context):
    """//////////////////////////////////////

    //////////////////////////////////////
    Workflows
    //////////////////////////////////////

    Get a specific workflow from an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListWorkflows(self, request, context):
    """List all the workflows.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostWorkflows(self, request, context):
    """Add a workflow to an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchWorkflows(self, request, context):
    """Patch one or more workflows.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteWorkflow(self, request, context):
    """Delete a single workflow.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteWorkflows(self, request, context):
    """Delete multiple workflows in one request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostWorkflowResults(self, request, context):
    """Predict using a workflow.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKey(self, request, context):
    """//////////////////////////////////////

    //////////////////////////////////////
    API Keys
    //////////////////////////////////////

    Get a specific key from an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListKeys(self, request, context):
    """List all the keys.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAppKeys(self, request, context):
    """List keys by app_id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteKey(self, request, context):
    """Search over the keys to find one or more you're looking for.
    This leverage the "body" parameter because we also have page and
    per_page as url query param variables in this request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostKeys(self, request, context):
    """Add a key to an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchKeys(self, request, context):
    """Patch one or more keys.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetApp(self, request, context):
    """//////////////////////////////////////
    Apps
    //////////////////////////////////////

    Get a specific app from an app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListApps(self, request, context):
    """List all the apps.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteApp(self, request, context):
    """Search over the apps to find one or more you're looking for.
    This leverage the "body" parameter because we also have page and
    per_page as url query param variables in this request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostApps(self, request, context):
    """Add a app to an app.
    This needs to load the default workflow to make a copy, validating all the models in it, and
    then writing the new workflow back to this new app.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PatchApps(self, request, context):
    """Patch one or more apps.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostSearches(self, request, context):
    """Execute a new search and optionally save it.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListStatusCodes(self, request, context):
    """//////////////////////////////////////

    //////////////////////////////////////
    Status Codes
    //////////////////////////////////////

    List all status codes.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatusCode(self, request, context):
    """Get more details for a status code.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_V2Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetConceptCounts': grpc.unary_unary_rpc_method_handler(
          servicer.GetConceptCounts,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetConceptCountsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptCountResponse.SerializeToString,
      ),
      'GetConcept': grpc.unary_unary_rpc_method_handler(
          servicer.GetConcept,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetConceptRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleConceptResponse.SerializeToString,
      ),
      'ListConcepts': grpc.unary_unary_rpc_method_handler(
          servicer.ListConcepts,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListConceptsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse.SerializeToString,
      ),
      'PostConceptsSearches': grpc.unary_unary_rpc_method_handler(
          servicer.PostConceptsSearches,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostConceptsSearchesRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse.SerializeToString,
      ),
      'PostConcepts': grpc.unary_unary_rpc_method_handler(
          servicer.PostConcepts,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostConceptsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse.SerializeToString,
      ),
      'PatchConcepts': grpc.unary_unary_rpc_method_handler(
          servicer.PatchConcepts,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchConceptsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiConceptResponse.SerializeToString,
      ),
      'GetInputCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetInputCount,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetInputCountRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleInputCountResponse.SerializeToString,
      ),
      'GetInput': grpc.unary_unary_rpc_method_handler(
          servicer.GetInput,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetInputRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleInputResponse.SerializeToString,
      ),
      'ListInputs': grpc.unary_unary_rpc_method_handler(
          servicer.ListInputs,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListInputsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse.SerializeToString,
      ),
      'PostInputs': grpc.unary_unary_rpc_method_handler(
          servicer.PostInputs,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostInputsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse.SerializeToString,
      ),
      'PatchInputs': grpc.unary_unary_rpc_method_handler(
          servicer.PatchInputs,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchInputsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse.SerializeToString,
      ),
      'DeleteInput': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteInput,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteInputRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'DeleteInputs': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteInputs,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteInputsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'PostModelOutputs': grpc.unary_unary_rpc_method_handler(
          servicer.PostModelOutputs,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelOutputsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiOutputResponse.SerializeToString,
      ),
      'GetModel': grpc.unary_unary_rpc_method_handler(
          servicer.GetModel,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse.SerializeToString,
      ),
      'GetModelOutputInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelOutputInfo,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse.SerializeToString,
      ),
      'ListModels': grpc.unary_unary_rpc_method_handler(
          servicer.ListModels,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListModelsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelResponse.SerializeToString,
      ),
      'PostModelsSearches': grpc.unary_unary_rpc_method_handler(
          servicer.PostModelsSearches,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelsSearchesRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelResponse.SerializeToString,
      ),
      'PostModels': grpc.unary_unary_rpc_method_handler(
          servicer.PostModels,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse.SerializeToString,
      ),
      'PatchModels': grpc.unary_unary_rpc_method_handler(
          servicer.PatchModels,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchModelsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelResponse.SerializeToString,
      ),
      'DeleteModel': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteModel,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteModelRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'DeleteModels': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteModels,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteModelsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'ListModelInputs': grpc.unary_unary_rpc_method_handler(
          servicer.ListModelInputs,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListModelInputsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiInputResponse.SerializeToString,
      ),
      'GetModelVersion': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelVersion,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelVersionRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelVersionResponse.SerializeToString,
      ),
      'ListModelVersions': grpc.unary_unary_rpc_method_handler(
          servicer.ListModelVersions,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListModelVersionsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiModelVersionResponse.SerializeToString,
      ),
      'PostModelVersions': grpc.unary_unary_rpc_method_handler(
          servicer.PostModelVersions,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelVersionsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelResponse.SerializeToString,
      ),
      'DeleteModelVersion': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteModelVersion,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteModelVersionRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'GetModelVersionMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelVersionMetrics,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetModelVersionMetricsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelVersionResponse.SerializeToString,
      ),
      'PostModelVersionMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.PostModelVersionMetrics,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostModelVersionMetricsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleModelVersionResponse.SerializeToString,
      ),
      'GetWorkflow': grpc.unary_unary_rpc_method_handler(
          servicer.GetWorkflow,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetWorkflowRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleWorkflowResponse.SerializeToString,
      ),
      'ListWorkflows': grpc.unary_unary_rpc_method_handler(
          servicer.ListWorkflows,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListWorkflowsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiWorkflowResponse.SerializeToString,
      ),
      'PostWorkflows': grpc.unary_unary_rpc_method_handler(
          servicer.PostWorkflows,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostWorkflowsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiWorkflowResponse.SerializeToString,
      ),
      'PatchWorkflows': grpc.unary_unary_rpc_method_handler(
          servicer.PatchWorkflows,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchWorkflowsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiWorkflowResponse.SerializeToString,
      ),
      'DeleteWorkflow': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteWorkflow,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteWorkflowRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'DeleteWorkflows': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteWorkflows,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteWorkflowsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'PostWorkflowResults': grpc.unary_unary_rpc_method_handler(
          servicer.PostWorkflowResults,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostWorkflowResultsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostWorkflowResultsResponse.SerializeToString,
      ),
      'GetKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetKey,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetKeyRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleKeyResponse.SerializeToString,
      ),
      'ListKeys': grpc.unary_unary_rpc_method_handler(
          servicer.ListKeys,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListKeysRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse.SerializeToString,
      ),
      'ListAppKeys': grpc.unary_unary_rpc_method_handler(
          servicer.ListAppKeys,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListAppKeysRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse.SerializeToString,
      ),
      'DeleteKey': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteKey,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteKeyRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'PostKeys': grpc.unary_unary_rpc_method_handler(
          servicer.PostKeys,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostKeysRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse.SerializeToString,
      ),
      'PatchKeys': grpc.unary_unary_rpc_method_handler(
          servicer.PatchKeys,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchKeysRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiKeyResponse.SerializeToString,
      ),
      'GetApp': grpc.unary_unary_rpc_method_handler(
          servicer.GetApp,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetAppRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleAppResponse.SerializeToString,
      ),
      'ListApps': grpc.unary_unary_rpc_method_handler(
          servicer.ListApps,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListAppsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiAppResponse.SerializeToString,
      ),
      'DeleteApp': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteApp,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.DeleteAppRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.BaseResponse.SerializeToString,
      ),
      'PostApps': grpc.unary_unary_rpc_method_handler(
          servicer.PostApps,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostAppsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiAppResponse.SerializeToString,
      ),
      'PatchApps': grpc.unary_unary_rpc_method_handler(
          servicer.PatchApps,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PatchAppsRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiAppResponse.SerializeToString,
      ),
      'PostSearches': grpc.unary_unary_rpc_method_handler(
          servicer.PostSearches,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.PostSearchesRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiSearchResponse.SerializeToString,
      ),
      'ListStatusCodes': grpc.unary_unary_rpc_method_handler(
          servicer.ListStatusCodes,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.ListStatusCodesRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.MultiStatusCodeResponse.SerializeToString,
      ),
      'GetStatusCode': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatusCode,
          request_deserializer=proto_dot_clarifai_dot_api_dot_service__pb2.GetStatusCodeRequest.FromString,
          response_serializer=proto_dot_clarifai_dot_api_dot_service__pb2.SingleStatusCodeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'clarifai.api.V2', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
